services:
  todolist_app:
    container_name: todolist-app-container
    build: .
    image: todolist-app:latest
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      - internalnet #default but we can specify it

networks:
  internalnet:
    driver: bridge
